services:
  db:
    container_name: data
    image: postgres

    ports:
      - 5432:5432

    networks:
      api-db:
      identity-db:

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    restart: always
    healthcheck:
      test: [ "CMD", "pg_isready"]
      interval: 20s
      timeout: 3s
      retries: 10

    volumes:
      - db-data:/var/lib/postgresql/data